<% project_name = 'in-the-cards' %>

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>

development:
  <<: *default
  database: <%= in-the-cards %>_development

test:
  <<: *default
  database: <%= in-the-cards %>_test
